import type { Metadata } from "next";
import Link from "next/link";
import { getModel } from "@/app/lib/forecastData";

export const metadata: Metadata = {
  title: "Forecast changelog",
  description: "Every change to the OnPoint Politics 2026 forecast: new polls, re-runs and model changes, by date.",
  alternates: { canonical: "/forecast/changelog" },
};

type Tag = "Polls" | "Model" | "Re-run" | "Site";
type Entry = { date: string; tag: Tag; title: string; text: string };

// Newest first. One line per entry: date (ISO), tag, title, then one or two sentences.
const ENTRIES: Entry[] = [
  { date: "2026-10-09", tag: "Polls", title: "Florida, Michigan, Pennsylvania and Wisconsin", text: "Added Targoz Market Research in Florida, Sept. 28 to Oct. 4, for a sponsor connected to the Heritage Foundation and so weighted as a Republican poll: Donalds 52, Jolly 42, sample size not yet published; and Z to A Research for Rust Belt Rising, a Democratic aligned group, Sept. 28 to Oct. 1: Michigan El-Sayed 49, Rogers 42 and Benson 50, James 40; Pennsylvania Shapiro 53, Garrity 34; Wisconsin Crowley 49, Tiffany 44. Florida governor Donalds +1.7, Jolly 37 percent, from +0.8 and 43 percent; Michigan governor Benson +7.8; Michigan Senate El-Sayed +5.2; Wisconsin governor Crowley +5.2; Pennsylvania governor Shapiro +25.4. Senate control 88 percent counting Osborn and 86 percent without; governor control 92 percent." },
  { date: "2026-10-09", tag: "Polls", title: "Morning sweep: Iowa and Maine", text: "Added Emerson College and Nexstar in Iowa, Oct. 5 to 6, 650 likely voters: Hinson 47, Turek 45 for Senate and Sand 49, Lahn 45 for governor; and The Washington Post in Maine, Sept. 30 to Oct. 5: Jackson 50, Collins 46 for Senate and Pingree 49, Charles 36 for governor, sample size not yet published. The St. Pete Polls Florida sample is now 836 likely voters. Iowa Senate Turek +1.3, 59 percent, from +2.3 and 66 percent; Iowa governor Sand +8.1, from +10.6; Maine Senate Jackson +4.0, 79 percent, from +3.4; Maine governor Pingree +12.2. Senate control 88 percent counting Osborn and 85 percent without; governor control 92 percent; House control 95 percent with a median of 247 Democratic seats." },
  { date: "2026-10-09", tag: "Polls", title: "Evening sweep: North Carolina, Ohio, Florida, Oregon and more", text: "Added East Carolina University in North Carolina, Sept. 30 to Oct. 3, Cooper 50, Whatley 43; co/efficient in Ohio, Oct. 5 to 6, Husted 44, Brown 43 for Senate and Ramaswamy 45, Acton 43 for governor; St. Pete Polls in Florida, Oct. 5 to 7, Moody 47, Nixon 45 and Donalds 45, Jolly 45, sample size not yet published; DHM Research for The Oregonian, Kotek 46, Drazan 44; Guidant for Public First Action governor results in Texas, Abbott 46, Hinojosa 44, and Michigan, Benson 50, James 45; the Alaska Survey Research governor final round, Kreiss-Tomkins 54, Wilson 46; the Maine People's Resource Center governor poll; and PPP in New York 18, Ryan 52, Auringer 35. Ohio governor Acton +3.9, 78 percent, from +5.6 and 87 percent; Ohio Senate Brown +4.4, 81 percent, from +4.9; Florida Senate Moody +3.1, from +4.3; Florida governor Donalds +0.9, Jolly 43 percent; Oregon governor Kotek +9.9; Michigan governor Benson +7.3. Senate control 88 percent counting Osborn and 85 percent without; governor control 93 percent; House control 95 percent with a median of 247 Democratic seats." },
  { date: "2026-10-08", tag: "Model", title: "Campaign finance updated for every Senate and governor race", text: "New fundraising and cash on hand figures checked October 8 replace the September finance records. Governor races use the average of each side's share of money raised and of cash on hand; Florida counts all accounts, including the candidates' political committees. Senate races use money raised plus outside spending for each side. Races whose figures are not comparable keep their previous records. The 24 races whose finance term moved were re-run. South Carolina Senate Graham +0.8, from +0.1; Minnesota governor Klobuchar +12.5; Michigan governor Benson +7.9; Maine governor Pingree +11.3; Texas governor Abbott +2.5. Senate control 89 percent counting Osborn and 86 percent without; governor control 93 percent." },
  { date: "2026-10-08", tag: "Model", title: "Arkansas 2: Hendrix poll corrected by the firm's own Arkansas miss", text: "Hendrix College's statewide Arkansas poll from the same week and method had Shoffner ahead of Cotton by 3, about 17 points more Democratic than every other poll of the race, and its governor poll ran about 9 points more Democratic than the race average. Its Arkansas 2 poll, Jones 48 to Hill 44, is now corrected by that measured miss instead of the smaller national house effect, which reads it as about Hill +10. Arkansas 2 moves to Hill +4.6, Lean Republican, Jones 23 percent. House control 95 percent with a median of 247 Democratic seats." },
  { date: "2026-10-08", tag: "Polls", title: "Every House district searched, district polls adjusted for pollster lean", text: "A second sweep covered the other 368 House districts and found 67 more general election polls, so 190 district polls in 89 districts are now on record. Nonpartisan district polls now carry the same pollster house effect the Senate and governor averages use, and Hendrix College polls are pooled under one name. A sample size that its own stated margin of error contradicts now enters at the size the margin implies: the Hendrix poll of Arkansas 2 lists 1,112 likely voters with a margin of error of 5.3 points, which fits about 340. Arkansas 2 Jones +2.1, 63 percent, from +3.1. Nebraska 2, California 48, California 22 and Arizona 1 tightened; Wisconsin 6 widened. House control 95 percent with a median of 248 Democratic seats." },
  { date: "2026-10-08", tag: "Polls", title: "Every poll of the 67 closest House seats", text: "A full sweep of every 2026 general election poll of the current nominees in the 67 Lean, Tilt and Lean Republican House seats found 123 district polls in 48 districts, most of them sponsored by a campaign, party or partisan group. Each district's polling entry was rebuilt from the full record: a 45 day recency half life, sample size weighting, partisan sponsors weighted at 0.7 and moved 1.5 points against the sponsor, informed ballots and polls at 20 percent undecided or more left out. Seven Florida districts, Colorado 5, New Jersey 2 and Texas 23 have polling in the model for the first time. The biggest moves: Texas 23 Herrera +3.3, Nebraska 1 Backemeyer +1.0, New Jersey 2 Van Drew +6.4, Missouri 2 and Minnesota 1 now near even. House control holds at 96 percent with a median of 248 Democratic seats." },
  { date: "2026-10-08", tag: "Polls", title: "Texas: UMass Lowell and YouGov", text: "Added UMass Lowell and YouGov in Texas, September 18 to 28, 850 likely voters: Talarico 45, Paxton 45, Brown 2 for Senate and Abbott 48, Hinojosa 44, Dixon 1 for governor. Abbott's favorable rating of 48 to 43 and job approval of 52 to 48 from the same survey join the candidate ratings. Texas Senate Talarico +2.8, 69 percent, from +2.8 and 71 percent; Texas governor Abbott +2.7, 72 percent, from +2.5. Senate control 89 percent counting Osborn and 86 percent without; governor control 93 percent." },
  { date: "2026-10-08", tag: "Polls", title: "Arizona governor: Hobbs campaign poll", text: "Added GQR for the Hobbs campaign in Arizona governor, September 30 to October 4, 600 likely voters: Hobbs 49, Biggs 45, Other 3, entered as a Democratic internal. It is the first Arizona governor poll since early September, so it carries most of the recent weight. Arizona governor Hobbs +9.9, 95 percent, from +13.7 and 99 percent. Governor control 93 percent; Senate and House unchanged. The Emerson New York poll for PIX11 was already in the morning update." },
  { date: "2026-10-08", tag: "Polls", title: "Morning sweep: CNN in Ohio and Iowa, Pennsylvania, New York, Texas, Michigan, Kansas and South Carolina", text: "Added CNN/SSRS in Ohio, September 29 to October 5, 760 likely voters: Brown 49, Husted 43 for Senate and Acton 50, Ramaswamy 42 for governor; CNN/SSRS in Iowa, 801 likely voters: Hinson 45, Turek 43 for Senate and Sand 51, Lahn 42 for governor; Quinnipiac in Pennsylvania, 1,159 likely voters: Shapiro 59, Garrity 34, and Susquehanna, 700 likely voters: Shapiro 52, Garrity 31; Emerson College for PIX11 in New York, 900 likely voters: Hochul 52, Blakeman 40; Guidant Polling for Public First Action in Texas, Talarico 47, Paxton 44, and Michigan, El-Sayed 48.5, Rogers 44 as the average of two ballots, both with field dates and sample size not published so 600 and an October 5 end date are placeholders; GBAO for the Hamilton campaign in Kansas, 600 likely voters, Hamilton 47.5, Marshall 42.5 as the average of two published figures; and FITSNews in South Carolina governor, 638 registered voters: Wilson 45, Johnson 35. House: NC-1 GQR for Davis and Neighborhood Research, TN-5 Impact Research for Molder, TX-2 Impact Research for Finnie. Iowa Senate Turek +2.2, 65 percent, from +3.4; Ohio Senate Brown +4.9, 84 percent; Ohio governor Acton +5.7, 87 percent, from +3.2; Kansas Senate Hamilton +1.6, 59 percent; South Carolina governor Wilson +6.1. Senate control 89 percent counting Osborn and 87 percent without; governor control 94 percent; House control 96 percent." },
  { date: "2026-10-08", tag: "Polls", title: "Evening sweep: Alaska and Michigan", text: "Added Alaska Survey Research in the Alaska Senate race, October 1 to 3, 1,512 likely voters: Peltola 47, Sullivan 45, Dan J. Sullivan 5, Heikes 3 in the first round, Peltola 51, Sullivan 49 in the final round; and Quantus Insights in Michigan, 762 likely voters released October 7: El-Sayed 48, Rogers 47, with field dates not published so the end date is a placeholder. Alaska Senate Peltola +1.5 in the final round, 60 percent, from +2.6; Michigan Senate El-Sayed +4.7, 82 percent. Senate control 88 percent counting Osborn and 86 percent without; governor control 93 percent; House control 96 percent." },
  { date: "2026-10-07", tag: "Model", title: "The 2026 electorate now shapes all three parts of the model", text: "The estimated 2026 midterm electorate, built from TPSI vote history and turnout, used to move county vote shares only in the census leg. It now also moves the approval leg and the polling leg county by county, with each leg keeping its statewide level so nothing is counted twice; the polling leg takes the pattern only in proportion to the presidential year races in its history. Eight polls entered twice as two ballot versions were merged into one row each, in Florida and New York governor, Iowa, Idaho, Michigan governor, North Carolina and Texas governor. Every Senate, governor and House race was re-run at 10,000 simulations. Statewide margins moved by less than half a point; Senate control 89 percent counting Osborn and 87 percent without, governor control 93 percent, House control 96 percent with a median of 248 Democratic seats." },
  { date: "2026-10-07", tag: "Polls", title: "Morning sweep: Iowa, New York and Arizona", text: "Added Suffolk University in Iowa, October 1 to 4, 500 likely voters: Turek 48, Hinson 44 for Senate and Sand 55, Lahn 43 for governor; Marist in New York, October 1 to 4, 1,361 registered voters: Hochul 53, Blakeman 42; and Arizona State University for Arizona governor, Hobbs 47, Biggs 34, among 1,300 registered voters. Iowa Senate Turek +3.4, 74 percent, from +2.6; Iowa governor Sand +11.2; New York governor Hochul +13.4; Arizona governor Hobbs +13.7, from +11.1. Senate control 89 percent counting Osborn and 86 percent without; governor control 92 percent; House unchanged at 96 percent." },
  { date: "2026-10-07", tag: "Polls", title: "Evening sweep: New Hampshire, California, Michigan and the House", text: "Added Saint Anselm College for AARP in New Hampshire, September 28 to 29, 1,042 likely voters: Pappas 51, Sununu 44 and Ayotte 52, Warmington 45; the Independent Voter Project and a Hilton campaign poll in California; Berkeley IGS from September; UMBC in Maryland; Public Policy Polling in Illinois; Mitchell Research for governor in Michigan; co/efficient in New York; and catch up polls in Georgia and North Carolina. Field dates and samples were corrected for Big Data Poll in Minnesota, the Maine People's Resource Center, SurveyUSA in New Mexico and Noble in Nevada. House polls added in KY 6, NY 17, VA 1, VA 5, VA 6, WA 3 and SC 1. California governor Becerra +15.6, from +23.3; New Hampshire Senate Pappas +11.9; New Hampshire governor Ayotte +8.1; Kentucky 6 moves to Tilt D. Senate control 89 percent counting Osborn and 86 percent without; governor control 92 percent; House control 96 percent with a median of 248 Democratic seats." },
  { date: "2026-10-06", tag: "Model", title: "Trump approval now comes from the TPSI likely voter electorate", text: "The stated registered voter net approval of minus 24 is removed. Every county's Trump approval is now leveled to the TPSI likely voter electorate itself: 40.3 percent approve and 57.1 percent disapprove, net minus 16.9, across 4,721 respondents through the October Benchmark. Every Senate, governor and House race was re-run at 10,000 simulations. Because the approval leg's national level stays on the generic ballot, statewide margins moved by less than a point outside the newly polled races, and House control holds at 96 percent with a median of 248 Democratic seats." },
  { date: "2026-10-06", tag: "Polls", title: "YouGov in seven states, and Mason-Dixon in Florida", text: "Added YouGov likely voter polls of the Senate and governor races in Texas, Florida, Michigan, Ohio, Kansas, Nebraska and New Hampshire, from 1,520 to 3,949 voters each, and Mason-Dixon for Telemundo in Florida, September 28 to October 1, 625 likely voters: Moody 50, Nixon 40 and Donalds 48, Jolly 41. Texas Senate Talarico +2.8, 70 percent; Texas governor Abbott +2.6, 71 percent; Michigan governor Benson +7.2; Nebraska governor Pillen +5.9; Florida governor Donalds +1.4, 61 percent, from a toss up; Florida Senate Moody +4.3, 77 percent. Senate control 89 percent counting Osborn and 85 percent without; governor control 92 percent." },
  { date: "2026-10-06", tag: "Polls", title: "Morning sweep: Maine, New Mexico and Nevada", text: "Re-run with Marist in Maine, October 1 to 4, 1,505 registered voters: Jackson 51, Collins 47 for Senate and Pingree 52, Charles 40, Bennett 6 for governor; SurveyUSA for KOB 4 in the New Mexico Senate race, Lujan 54, Marker 36; and Noble Predictive Insights in Nevada, Lombardo 42, Ford 40. The New Mexico and Nevada polls were released without field dates, and Nevada without a sample size, so those are placeholders. Maine Senate Jackson +3.2, 73 percent, from +3.7; Maine governor Pingree +11.4; New Mexico Senate Lujan +21.4; Nevada governor Lombardo +2.4, 64 percent, from a toss up. Senate control 88 percent counting Osborn and 85 percent without; governor control 92 percent; House control 96 percent." },
  { date: "2026-10-05", tag: "Polls", title: "Evening sweep: Michigan", text: "Re-run with Mitchell Research for CBS Detroit in Michigan, October 1, likely voters: El-Sayed 45.6, Rogers 41.4, the four minor party candidates 7 together. The sample size was not published, so 650 is entered to match its 3.8 point margin of error. Michigan Senate El-Sayed +5.3, 85 percent, from +4.8. Senate control 88 percent counting Osborn and 85 percent without; governor control 93 percent; House control 96 percent." },
  { date: "2026-10-05", tag: "Polls", title: "Quantus Insights is no longer treated as a partisan poll", text: "Every Quantus Insights poll in every state now counts as an independent poll rather than a Republican sponsored one. A partisan tag was meant for polls paid for by a campaign, party or partisan group, and Quantus publishes its own polls; its lean is now measured from its results like any other firm's, at about 1.9 points toward Republicans across 14 polls. Its polls now count toward each race's polling depth and are no longer moved by the sponsor adjustment. Nine races were re-run: Florida Senate Moody +3.9, 75 percent, from +3.4; Minnesota Senate Flanagan +7.8, from +8.6; Iowa Senate Turek +2.5, 68 percent, from +2.8; Alaska Senate Peltola +2.5, 68 percent, from +2.2; Arizona governor Hobbs +11.1. Senate control 88 percent counting Osborn and 85 percent without; governor control 93 percent; House control 96 percent." },
  { date: "2026-10-05", tag: "Model", title: "Gallup party identification returns as the census anchor; the House runs at 10,000", text: "Gallup party identification of 50 Democratic to 39 Republican among adults now anchors the census leg in every Senate, governor and House race. It is converted to a vote through the TPSI respondent database: every ACS cell's TPSI party mix is moved until the nation's adults identify 50 D, 39 R and 11 independent, and each cell and party then turns out at its DSMeridian likely voter propensity, which gives a likely voter vote of D+15.4. The approval and previous results legs stay on the national generic ballot at D+12. The House now uses the correlation calibration the Senate and governor races took on October 3: the shared national environment runs at half strength, each district takes its region's shock, and the spread removed goes back to the state shock, so every district is exactly as uncertain as before but states and regions move less as one. The House also runs at 10,000 simulations for the first time, on the October respondent database. Races moved toward Democrats by 0.4 points on average and at most 1.5, in safe seats; no race within 15 points moved more than 0.9. House control rises from 89 to 96 percent: about 2 points from Gallup and about 5 from the correlation calibration, with the median at 248 Democratic seats. Senate control 88 percent counting Osborn and 85 percent without; governor control 94 percent." },
  { date: "2026-10-05", tag: "Polls", title: "Sweep: New Hampshire, Maine, Kansas, New Mexico and NY-17", text: "Re-run with Rasmussen in New Hampshire, October 2 to 4, 979 likely voters: Pappas 49, Sununu 44; the Maine People's Resource Center poll released October 5, 684 registered voters: Jackson 49, Collins 47; the New York Times/Siena Kansas governor poll, September 22 to 30, 605 likely voters: Masterson 49, Holscher 44; and SurveyUSA for KOB 4 in New Mexico, released October 5, 567 likely voters: Haaland 47, Hull 41. The Maine and New Mexico polls were released without field dates, so their dates are placeholders. New Hampshire Senate Pappas +12.9; Maine Senate Jackson +3.6, 77 percent; Kansas governor Masterson +0.9, 56 percent; New Mexico governor Haaland +11.6. The House takes Emerson for PIX11 in NY-17, September 27 to 29: Conley 48, Lawler 46." },
  { date: "2026-10-04", tag: "Polls", title: "Evening sweep: Georgia, South Dakota and three House districts", text: "Re-run with Wedgewood Polls in Georgia, October 2 to 3, 600 likely voters: Ossoff 55, Collins 45 and Jackson 51, Lance Bottoms 49; and the Zenith Research poll for the Bengs campaign in South Dakota, released without field dates or a sample size: Rounds 44, Bengs 38. Georgia Senate Ossoff +10.8, 99 percent; Georgia governor Lance Bottoms +2.4, 69 percent; South Dakota Senate Rounds +13.0. The House takes campaign polls in TX-9, Mealer 45, Gutierrez 39; TX-10, Gober 48, Rourk 41; and VA-5, McGuire 46, Perriello 45. TX-9 moves to Mealer +7.3, 85 percent. Senate control 87 percent counting Osborn and 84 percent without; governor control 92 percent; House control 89 percent." },
  { date: "2026-10-04", tag: "Model", title: "October TPSI respondents join the model", text: "Every Senate and governor race was re-run at 10,000 simulations with the October TPSI Benchmark added to the respondent database: 529 analysis ready respondents, 4,767 in all. October is the most Democratic wave so far, D 56 to R 38 after the undecided allocation, and the pooled database moves from D+9.9 to D+10.7. Every October only question, from public figure favorables and twenty policy items to the 2028 vote and the generic ballot effect items, is now mapped onto every earlier respondent from their demographics and core political answers, each model checked against October respondents it did not see. Races moved toward Democrats by 0.1 points on average and at most 0.7, in the Iowa governor race. Senate control 87 percent counting Osborn and 84 percent without; governor control 93 percent; House control 90 percent." },
  { date: "2026-10-04", tag: "Polls", title: "Morning sweep: sixteen late September polls", text: "No poll was released overnight, but a check against the aggregators found sixteen September polls the model did not carry, and they are now in: in North Carolina, High Point, YouGov, Opinion Diagnostics for Common Cause, Quantus Insights and Rasmussen; in Ohio, Rasmussen and Quantus Insights; Trafalgar in Alaska; Big Data Poll in Michigan; InsiderAdvantage in the Georgia Senate race; UMass Lowell/YouGov in both Maine races; and the New York Times/Siena governor questions in Maine, Michigan and New Hampshire. The New York Times/Siena polls of October 3 now carry their published sample sizes and field dates. Alaska Senate Peltola +1.8, 63 percent, from +2.9; Ohio Senate Brown +3.5, 77 percent; North Carolina Senate Cooper +11.0. The House takes American Pulse in MT-1, Flint 45.9, Forstag 45.4, which moves to Flint +0.7. Senate control 86 percent counting Osborn and 83 percent without; governor control 93 percent; House control 90 percent." },
  { date: "2026-10-03", tag: "Polls", title: "Evening sweep: Montana, Massachusetts and five House districts", text: "Three statewide polls released in late September were missing and are now in: American Pulse for NonStop Local in Montana, September 19 to 24, about 600 Montanans: Alme 45.1, Bodnar 26.1, Bankhead 18.9; and MassINC for CommonWealth Beacon in Massachusetts, September 14 to 22, 800 likely voters: Healey 54, Minogue 32 and Markey 54, Deaton 28. Montana Senate Alme +19.5; the house effect refit also nudged both New Mexico races. The House takes NYT/Siena in Alaska at large, Begich 47, Hill 35; the Tulchin poll for the Dunlap campaign in ME-2, Dunlap 50, LePage 48; DCCC Analytics in OH-9 and WI-1, both tied at 48; and Lighthouse Research in UT-1, McAdams 63, Owen 21. ME-2 stays a toss up at 52 percent for Dunlap and OH-9 moves to Kaptur at 65 percent. No new statewide poll was released October 2 to 4 that the model did not already carry. Senate control 88 percent counting Osborn and 85 percent without; governor control 93 percent; House control 90 percent." },
  { date: "2026-10-03", tag: "Model", title: "Calibrated on the 2018 and 2022 midterms, 10,000 simulations", text: "Every Senate and governor race was re-run after a backtest on 139 Senate and governor races from 2018 and 2022, each fit on one cycle and scored on the other. The spread now depends on how well a race is polled: races with eight or more polling houses missed by less than the old spread said and thinly polled races by more, so the spread runs from 0.90 to 1.08 times its old size, and each race's own shock has the fatter tails real misses showed. In those cycles races in different regions shared no measurable miss, so the national vote shocks are halved and a small regional shock is added: Senate races now move together at about 0.17 instead of 0.62, and each race is exactly as uncertain as before. Each pollster's house effect is measured across all 59 polled races, shrunk and centered on zero so the average as a whole never moves, which cut the typical miss 31 days out from 6.3 to 6.1 points in the backtest; registered voter polls take the measured likely voter gap, 0.3 points this year. Inside the last three weeks the polls' floor rises to 0.64 on election day. No undecided break rule beat an even split, so undecided voters still split like decided ones. A data check now runs on every sweep and fixed three entries: the AARP poll in North Carolina at 1,115 likely voters, Stratus in the Texas governor race at 856, and DHM in Oregon. Each race is now simulated 10,000 times and each day's forecast is archived. Senate control 88 percent counting Osborn and 85 percent without; about 10 points of that rise comes from the lower correlation between races. Governor control 93 percent." },
  { date: "2026-10-03", tag: "Model", title: "Candidate favorability enters every Senate and governor race", text: "Each candidate's 2026 statewide favorable and unfavorable rating, or job approval for officeholders, was researched from public polls: 192 readings, with both candidates rated in 34 races. Across those races the Democratic minus Republican net rating explains how far the polls run from the model's fundamentals, correlation 0.57, and predicting each race from the others cut the typical miss by a quarter. The candidate term is now pulled toward what the ratings predict instead of toward zero, about 3.3 points of margin per 10 net points, so heavily polled races are still set by their polls and thinly polled races lean on the ratings. Campaign and partisan polls count 0.7 and move 1.5 net points against their sponsor. The largest moves are 0.7 points: California governor, Mississippi Senate, New Hampshire governor and South Carolina Senate. Senate control 72 percent counting Osborn and 71 percent without; governor control 89 percent." },
  { date: "2026-10-03", tag: "Model", title: "Every Senate and governor race re-run with a measured county top out", text: "A county can now run past the most or least Democratic it has been relative to its state, in the 2016, 2020 and 2024 presidential races and past races for the same office, only as far as counties actually did in 2022: 0.09 in log odds plus a quarter of its last presidential trend, the narrowest room that held 95 percent of the 2022 vote. The old hand set room was 0.15 plus half the eight year trend; 38 counties now top out instead of 3. A county's own past Senate and governor lean and a returning candidate's own county pattern were both tested on 2022 and made the county map worse, so neither was added. The re-run also takes this morning's polls: New York Times/Siena in Texas, Alaska, Ohio, Kansas and Iowa, CBS News/YouGov and Trafalgar in Maine. Senate control 72 percent counting Osborn and 71 percent without; governor control 89 percent." },
  { date: "2026-10-02", tag: "Polls", title: "Evening sweep: Alaska and NY-23", text: "Re-run with Quantus Insights in Alaska, released October 2, 758 likely voters: Sullivan 46.1, Peltola 45.5. Alaska Senate Peltola +0.9, 56 percent. The House takes the Cygnal poll for the Langworthy campaign in NY-23, Langworthy 54, Gies 33. Every other poll released since October 1 was already in. Senate control 73 percent counting Osborn and 72 percent without; governor control 90 percent; House control 90 percent." },
  { date: "2026-10-02", tag: "Polls", title: "Texas and Kansas Senate", text: "Both poll lists were checked against the full public record. Kansas adds Trafalgar, September 29 to October 1, 1,095 likely voters: Hamilton 44.4, Marshall 43.5, and Global Strategy Group, September 13 to 16: Hamilton 47, Marshall 43. Texas adds Pulse Decision Science, September 24 to 27: Paxton 48, Talarico 45, fills in Stratus Intelligence at 856 likely voters, and counts the Overton Insights poll once instead of twice. Texas Senate Talarico +1.9, 62 percent; Kansas Senate Marshall +0.9, 57 percent. Senate control 74 percent counting Osborn and 73 percent without." },
  { date: "2026-10-02", tag: "Polls", title: "Nebraska, Iowa and three House districts", text: "Re-run with co/efficient in Nebraska, September 28 to 30, 1,113 likely voters: Ricketts 45, Osborn 40 for Senate and Pillen 43, Walz 38 for governor; and Rasmussen in Iowa, September 28 to 30, 1,028 likely voters: Turek 47, Hinson 43. Nebraska Senate moves to Ricketts +1.1, 58 percent; Nebraska governor Pillen +9.4; Iowa Senate Turek +2.2, 65 percent. The House takes co/efficient in SC-1, the Cline internal in VA-6 and the Dembo internal in KY-6; KY-6 moves to Alvarado +0.7, 53 percent. Senate control 74 percent counting Osborn and 73 percent without; governor control 90 percent; House control 90 percent." },
  { date: "2026-10-02", tag: "Model", title: "Ad spending on file", text: "AdImpact aired spending through September 30 is now stored with each battleground Senate race: Republicans lead aired advertising by $61 million in Texas, $41 million in Ohio, $27 million in Maine, $17 million in Iowa, $15 million in Michigan and $12 million in Alaska, and hold 61 percent of future reservations. The model does not read ad spending, so the ten races re-run moved by 0.2 points or less. Senate control 74 percent counting Osborn and 72 percent without." },
  { date: "2026-10-02", tag: "Polls", title: "Vermont governor", text: "Re-run with State Navigate: Scott 45.7, Janoo 43.6, in a sample that recalls Scott +61 in 2024. Vermont governor Scott +10.6, 96 percent, from Scott +12.2, 98 percent. Governor control unchanged at 90 percent." },
  { date: "2026-10-02", tag: "Polls", title: "Minnesota Senate", text: "Re-run with Big Data Poll, likely voters with leaners: Flanagan 45.8, Tafoya 43.6, Whiting 5.2. Minnesota Senate Flanagan +8.3, 93 percent, from Flanagan +9.3, 95 percent. Senate control 74 percent counting Osborn and 71 percent without." },
  { date: "2026-10-02", tag: "Polls", title: "South Carolina Senate", text: "Re-run with InsiderAdvantage, September 28 to 29, 1,200 likely voters: Graham 46, Andrews 45, other 6. South Carolina Senate Graham +1.9, 64 percent, from Graham +2.3, 68 percent. Senate control 75 percent counting Osborn and 71 percent without." },
  { date: "2026-10-02", tag: "Polls", title: "Maine Senate", text: "Re-run with Wedgewood Polls, September 27 to October 1, 400 likely voters: Jackson 52, Collins 48. Maine Senate Jackson +3.3, 73 percent; Maine governor Pingree +13.1, unchanged. Senate control 74 percent counting Osborn and 71 percent without." },
  { date: "2026-10-02", tag: "Polls", title: "Texas, Michigan, Ohio, Pennsylvania and Alaska", text: "Re-run with Fox News in Texas, September 24 to 28, Talarico 51, Paxton 49 and Abbott 52, Hinojosa 47; Rasmussen in Texas, September 28 to 29; Trafalgar in Michigan, September 28 to 30; InsiderAdvantage in Ohio, September 28 to 29; Bravo Group for PennLive in Pennsylvania; and Cygnal in Alaska. Texas Senate Talarico +2.2, 65 percent; Michigan Senate El-Sayed +4.8, 79 percent; Ohio Senate Brown +5.0, 83 percent. The House takes the Washington Post and Schar School polls of VA-1 and VA-5 and DHM for OPB in WA-3; VA-1 moves to the Democrat at +1.1. Senate control 73 percent counting Osborn and 70 percent without; governor control 90 percent; House control 90 percent." },
  { date: "2026-10-02", tag: "Model", title: "Campaign finance refreshed", text: "Every Senate, governor and House race was re-run with refreshed campaign finance. Governor money is updated from the newest state filings in Florida, Ohio, Wisconsin, Pennsylvania, Minnesota, Maine and Arkansas, and six records were corrected: Arizona and Kansas no longer count a pledge and an ad reservation their sources excluded, Vermont and Rhode Island now compare both candidates on the same basis and date, Tennessee takes exact filed totals, and South Dakota's money term is off until the Democratic nominee files. Ohio now compares 2026 donations on both sides, Acton $16.5 million and Ramaswamy $14.4 million before his own $25 million, and moves to Acton +5.8, 87 percent. Kansas governor moves to Masterson +2.1. No Senate or House nominee has filed with the FEC since the last update; quarterly reports are due October 15. Senate control 75 percent counting Osborn and 72 percent without; governor control 90 percent; House control 90 percent." },
  { date: "2026-10-02", tag: "Polls", title: "Twelve races take new polls", text: "Re-run with Fox News in Michigan and Iowa, September 24 to 28; co/efficient in Maine, September 28 to 30; Suffolk for USA TODAY in Ohio, September 23 to 27; Trafalgar in New Hampshire, September 26 to 27; DHM for OPB in Oregon, September 17 to 27; and RMG for Alabama Policy Action, September 21 to 25. Maine Senate Jackson +1.7, 62 percent; Ohio governor Acton +5.3, 84 percent; Ohio Senate Brown +6.2; Michigan Senate El-Sayed +5.7; Iowa Senate Turek +1.1. NY-17 takes Emerson for PIX11, Democrat 48, Republican 46. Senate control 75 percent counting Osborn and 72 percent without; governor control 89 percent; House control 90 percent." },
  { date: "2026-10-02", tag: "Model", title: "Counties and turnout follow real midterms", text: "Every Senate, governor and House race was re-run after a 2024 backtest of the method in eleven states. Each county now starts from its 2024 presidential lean and moves the way counties actually moved in the 2018 and 2022 midterms, with the rest of the model's county pattern held to the spread those midterms showed; the assumed trend carry is replaced by the measured one, a small reversal. Each state's turnout now blends the vote history model with its own midterm record, which predicted 2022 better than either alone. No poll was adjusted and no statewide margin moved more than 0.3 points, but the county maps did: Miami Dade goes from D+11.7 to D+2.3 for Nixon and Starr from D+27.0 to D+20.4 for Talarico, and Florida's Hispanic counties now run about 5 points ahead of the state's swing instead of 11 to 14. Senate control 77 percent counting Osborn and 75 percent without; governor control 88 percent; House control 90 percent." },
  { date: "2026-10-01", tag: "Model", title: "Early vote party estimate, version 2", text: "The Early Vote page's party estimate for the fourteen states that report no party now starts from the forecast's own D+12 electorate, voter type by voter type, and gives each type its chance of voting by mail or early in person under its state's ballot rules. Vermont and Hawaii mail every voter a ballot, so their requests are now read as the voter file: Vermont moves from D+59 to D+35 and Hawaii from D+53 to D+20. The mail skew is checked against Florida, North Carolina, Pennsylvania and New Jersey, and Michigan's published ages now reweight its estimate. Nationwide requests read D+19.4 counting reported party and the estimate." },
  { date: "2026-10-01", tag: "Model", title: "County trends carry forward", text: "Every Senate, governor and House race was re-run. Each county now carries forward its 2016 to 2024 trend relative to its state, weighted toward the latest cycle and scaled up or down by whether its 2026 primary electorate moved the same way, and the office history leg now carries more of the state's own trend for the office. The trend moves votes between counties, not the statewide level: Miami Dade moves to the right and Duval to the left, the Rio Grande Valley moves right and the Dallas exurbs left, and statewide margins moved by at most 0.3 points. Senate control 78 percent counting Osborn and 76 percent without; governor control 89 percent; House control 89 percent." },
  { date: "2026-10-01", tag: "Polls", title: "North Carolina Senate", text: "Re-run with Big Data Poll's Tar Heel State Poll, September 27 to 29, 642 likely voters with leaners: Cooper 50.8, Whatley 38.5. Cooper +12.7, 99 percent." },
  { date: "2026-10-01", tag: "Model", title: "D+12 generic ballot and net -24 approval", text: "Every Senate, governor and House race was re-run on a D+12 generic ballot, now the one national anchor for both the approval leg and the census leg, and on a net Trump approval of -24 among registered voters. TPSI respondents put likely voters about a point more disapproving, and the simulated 2026 electorates come out at about -26. Senate control 77 percent counting Osborn and 74 percent without; governor control 87 percent; House control 89 percent." },
  { date: "2026-09-30", tag: "Polls", title: "Michigan, Iowa, Wisconsin and Nebraska", text: "Michigan Senate and governor took NPR/Marist: El-Sayed 51, Rogers 44 and Benson 53, James 41. Iowa Senate took Quantus Insights: Hinson 48.5, Turek 46.6, now a toss up. Wisconsin governor took Marquette: Crowley 49, Tiffany 46. Nebraska governor took Lake Research for the Walz campaign: Pillen 40, Walz 40." },
  { date: "2026-09-30", tag: "Model", title: "County citizenship and realistic limits", text: "Every Senate, governor and House race was re-run. Each county now counts its own citizen adults by race group from the Census Bureau's 2020 to 2024 citizen voting age tables, in place of one national rate. Counties can no longer run past the most or least Democratic they have ever been relative to their state, turnout stays within what each county has actually cast, and Black, Latino and Asian voters stay inside a realistic statewide range built from Pew's validated 2020 and 2024 vote and TPSI respondents. Senate control 78 percent counting Osborn and 76 percent without; governor control 87 percent; House control 89 percent." },
  { date: "2026-09-30", tag: "Polls", title: "Minnesota Senate", text: "Re-run with InsiderAdvantage, September 28 to 29, 1,200 likely voters: Flanagan 46, Tafoya 45. Flanagan +9.5, 95 percent." },
  { date: "2026-09-29", tag: "Model", title: "Why voters turn out, and who splits their ticket", text: "Every Senate, governor and House race was re-run with a voter behavior layer built from the TPSI respondent file. Each simulated voter type now carries its own reasons to turn out, read from stated intent, ballot plans, past voting, friends who vote, approval intensity, economic strain and the niche questions, and every simulation moves those motivations up or down, so a low commitment year or soft Trump approvers staying home changes who votes. States with both a Senate and a governor race share a state level shock set by how often TPSI respondents switch parties, and the model estimates each race's split ticket voters. The House also takes 36 new district polls in 29 districts, including a Republican poll of CO-8 by McLaughlin and Associates with Evans 48, Rutinel 46. Senate control 79 percent counting Osborn and 77 percent without; governor control 86 percent; House control 89 percent." },
  { date: "2026-09-29", tag: "Polls", title: "Ohio governor", text: "Re-run with the governor ballot from Big Data Poll's Buckeye State Poll, September 26 to 27: Ramaswamy 47.9, Acton 46.8. Acton +2.5, 68 percent." },
  { date: "2026-09-29", tag: "Model", title: "Third party candidates and TPSI respondents", text: "Every Senate, governor and House race was re-run. Third party candidates no longer fall to zero when a race's polls skip the question: their share now blends what a candidate of that ballot label usually draws, the state's own past third party vote for the office, and only the polls that asked. The census leg now reads the unified TPSI respondent file, counts citizen adults, and adds a small pooled effect for each state. Senate control 78 percent counting Osborn and 77 percent without; governor control 88 percent; House control 90 percent." },
  { date: "2026-09-29", tag: "Model", title: "Office history, fundamentals and primaries", text: "Every Senate, governor and House race was re-run. Five points of weight moved from the polls to the fundamentals, the 2026 primaries now carry more of the candidate signal, and Senate and governor races read the state's own last two results for that office, moved to this year's environment. Senate control 78 percent counting Osborn and 75 percent without; governor control 87 percent; House control 90 percent." },
  { date: "2026-09-29", tag: "Polls", title: "Michigan Senate and governor", text: "Both Michigan races were re-run with Cygnal (R) and Beacon Research (D) for Michigan Enjoyer, September 18 to 21, 600 likely voters: El-Sayed 45, Rogers 40 and Benson 45, James 38. Senate: El-Sayed +4.7, 80 percent. Governor: Benson +7.3, 90 percent. Senate control 79 percent counting Osborn; governor control 86 percent." },
  { date: "2026-09-29", tag: "Polls", title: "Ohio Senate and governor", text: "Both Ohio races were re-run with Big Data Poll, 682 likely voters, Brown 46.9, Husted 42.5, and NPR/Marist, September 24 to 27, 1,298 registered voters: Brown 51, Husted 43 and Acton 50, Ramaswamy 44. Senate: Brown +6.6, 88 percent. Governor: Acton +4.0, 77 percent. Senate control 80 percent counting Osborn; governor control 86 percent." },
  { date: "2026-09-28", tag: "Polls", title: "Florida Senate and governor", text: "Both Florida races were re-run with the Change Research poll of September 26 to 28, 1,063 likely voters: Jolly 48, Donalds 47 for governor and Moody 48, Nixon 47 for Senate. The governor average now carries every public poll of the race, 21 in all, including Stetson University at Donalds 51, Jolly 39. Governor: Jolly +0.5, a toss up at 52 percent. Senate: Moody +5.1. Governor control odds 84 percent." },
  { date: "2026-09-28", tag: "Site", title: "OnPoint Politics", text: "The site is now OnPoint Politics. TPSI polls are still fielded by The Public Sentiment Institute, and every forecast number carries over unchanged." },
  { date: "2026-09-28", tag: "Re-run", title: "House forecast re-run", text: "The House was re-run with every statewide change from today, so the district simulations share the same national and demographic shocks as the Senate and governor runs." },
  { date: "2026-09-28", tag: "Polls", title: "Kansas Senate and governor", text: "Both Kansas races were re-run with new polls from Wedgewood, GBAO and Tavern Research." },
  { date: "2026-09-28", tag: "Model", title: "Governor depolarization", text: "Governor races now respond to about 60 percent of the national swing and of the state's partisan lean, beta 0.6 and lambda 0.6, with the rest moved to state level uncertainty, because governor races are more local. Every governor race was re-run." },
  { date: "2026-09-28", tag: "Polls", title: "Nevada and Arizona governor", text: "Both races were re-run with new polls." },
  { date: "2026-09-28", tag: "Polls", title: "Georgia governor", text: "Re-run with InsiderAdvantage, 1,200 likely voters, 48 to 46, and YouGov, 3,299 likely voters, 46 to 44." },
  { date: "2026-09-28", tag: "Polls", title: "Vermont governor", text: "Re-run with the Braun Research poll: Scott 44, Janoo 34, among 817 likely voters." },
];

const fmtDate = (iso: string) => new Date(iso + "T12:00:00").toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
const pct = (p: number) => `${+(p * 100).toFixed(2)}%`;

export default function Page() {
  const model = getModel();
  const ch = model.chambers;
  const days = [...new Set(ENTRIES.map((e) => e.date))];
  return (
    <div className="opp">
      <style>{CSS}</style>
      <nav className="crumbs" aria-label="Breadcrumb">
        <Link href="/">Home</Link><span className="sep">/</span><Link href="/forecast">Forecast</Link><span className="sep">/</span><span>Changelog</span>
      </nav>
      <header className="ph">
        <div className="eye g">Forecast changelog</div>
        <h1>What changed in the <em>forecast</em></h1>
        <p className="lede">Every new poll, re-run and model change, newest first. The headline odds below are read from the current forecast build.</p>
        <div className="pmeta">
          <span><b className="mono">{ENTRIES.length}</b> entries</span>
          <span>Updated <b>{fmtDate(model.meta.updated)}</b></span>
          <Link className="btn sm" href="/forecast">The forecast</Link>
          <Link className="btn sm" href="/forecast/methodology">Methodology</Link>
        </div>
      </header>

      <div className="layout">
        <div className="cl-stack">
          {days.map((d) => {
            const items = ENTRIES.filter((e) => e.date === d);
            return (
              <section key={d} className="card">
                <div className="card-h"><h3>{fmtDate(d)}</h3><span className="eye" style={{ marginLeft: "auto" }}>{items.length} {items.length === 1 ? "change" : "changes"}</span></div>
                <ol className="cl-list">
                  {items.map((e, i) => (
                    <li key={i}>
                      <span className="cl-tag">{e.tag}</span>
                      <div><b>{e.title}</b><p>{e.text}</p></div>
                    </li>
                  ))}
                </ol>
              </section>
            );
          })}
        </div>

        <aside className="side">
          <div className="card">
            <div className="card-h"><h3>Current odds</h3><span className="eye" style={{ marginLeft: "auto" }}>D control</span></div>
            <div className="stat"><div className="k">Senate, counting Osborn</div><div className="v d">{pct(ch.senate.demControl)}</div></div>
            <div className="stat"><div className="k">House</div><div className="v d">{pct(ch.house.demControl)}</div></div>
            <div className="stat"><div className="k">Governors</div><div className="v d">{pct(ch.governor.demControl)}</div></div>
          </div>
          <div className="callout">
            <div className="eye">How to read it</div>
            A re-run rebuilds the race from its poll file and runs all {model.meta.sims.toLocaleString()} simulations again. <Link href="/forecast/methodology" style={{ textDecoration: "underline" }}>How the model works</Link>.
          </div>
        </aside>
      </div>
    </div>
  );
}

const CSS = `
.opp .cl-stack { display: grid; gap: 16px; min-width: 0; }
.opp .cl-list { list-style: none; margin: 0; padding: 0; }
.opp .cl-list li { display: grid; grid-template-columns: 76px minmax(0,1fr); gap: 14px; padding: 14px 18px; border-top: 1px solid var(--line); }
.opp .cl-list li:first-child { border-top: 0; }
.opp .cl-list b { font: 700 15px/1.3 var(--font-d); letter-spacing: -.01em; color: var(--hi); }
.opp .cl-list p { margin: 4px 0 0; font-size: 14px; line-height: 1.6; color: var(--ink2); max-width: 70ch; }
.opp .cl-tag { align-self: start; justify-self: start; margin-top: 2px; padding: 3px 8px; border-radius: 999px; border: 1px solid var(--line2); background: var(--glass2);
  font: 700 10px var(--font-m); letter-spacing: .1em; text-transform: uppercase; color: var(--ink2); }
@media (max-width: 600px) { .opp .cl-list li { grid-template-columns: 1fr; gap: 6px; } }
`;
