/**
 * Generates the Florida election-night seed data from the TPSI scenario-engine
 * baseline (app/floridaprimary/flData.json) plus county FIPS from CivicAPI.
 *
 *   node scripts/gen_fl_forecast.mjs
 *
 * Writes app/results/_data/flCountyGeo.ts and app/results/_data/flCountyForecast.ts.
 * Re-run whenever flData.json is regenerated; never hand-edit the outputs.
 *
 * FIPS come from race 86349's region_results, which is also the feed the board
 * reads on the night, so county keys are guaranteed to line up.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const RACE_ID = 86349;
const OUT_DIR = path.join(ROOT, "app/results/_data");

const data = JSON.parse(
  fs.readFileSync(path.join(ROOT, "app/floridaprimary/flData.json"), "utf8")
);

const CANDS = ["Donalds", "Fishback", "Collins", "Renner", "Other"];
const KEYS = ["donalds", "fishback", "collins", "renner", "other"];

async function fipsByName() {
  const res = await fetch(`https://civicapi.org/api/v2/race/${RACE_ID}`);
  if (!res.ok) throw new Error(`CivicAPI ${res.status}`);
  const j = await res.json();
  const map = {};
  for (const r of Object.values(j.region_results || {})) {
    if (r?.name && r?.fips) map[String(r.name).toUpperCase()] = String(r.fips);
  }
  if (Object.keys(map).length !== 67) {
    throw new Error(`expected 67 counties from CivicAPI, got ${Object.keys(map).length}`);
  }
  return map;
}

const round = (n, p = 4) => Number(n.toFixed(p));

function build(fips) {
  const counties = Object.entries(data.counties).map(([key, c]) => {
    const shares = Object.fromEntries(CANDS.map((n, i) => [KEYS[i], c[n]]));
    const ordered = KEYS.map((k) => [k, shares[k]])
      .filter(([k]) => k !== "other")
      .sort((a, b) => b[1] - a[1]);

    const margin = shares.donalds - shares.fishback;
    // flData's lo/hi is a 90% band on the Donalds−Fishback margin; recentre it
    // on the point estimate so the two can never disagree.
    const halfWidth = (c.hi - c.lo) / 2;
    const ci90 = [round(margin - halfWidth, 2), round(margin + halfWidth, 2)];

    return {
      key,
      fips: fips[c.name.toUpperCase()],
      name: c.name,
      region: c.region,
      projectedTurnout: Math.round(c.votes),
      shareOfElectorate: round((c.votes / data.statewide.total) * 100, 3),
      ...Object.fromEntries(KEYS.map((k) => [k, round(shares[k], 2)])),
      margin: round(margin, 2),
      leader: ordered[0][0],
      runnerUp: ordered[1][0],
      ci90,
      tooCloseToCall: ci90[0] < 0 && ci90[1] > 0,
      ...Object.fromEntries(
        KEYS.map((k) => [`${k}Votes`, Math.round((c.votes * shares[k]) / 100)])
      ),
      interviews: c.nobs,
    };
  });

  counties.sort((a, b) => b.projectedTurnout - a.projectedTurnout);
  return counties;
}

function emitGeo() {
  const entries = Object.entries(data.geo)
    .map(([k, d]) => `  ${JSON.stringify(k)}: ${JSON.stringify(d)},`)
    .join("\n");

  return `// Florida county SVG geometry, extracted from the TPSI Florida scenario engine
// (app/floridaprimary/flData.json). Keyed by UPPERCASE county name.
// GENERATED by scripts/gen_fl_forecast.mjs — DO NOT EDIT BY HAND.

export const FL_MAP_VIEWBOX = "0 0 ${data.w} ${data.h}";

export const FL_COUNTY_PATHS: Record<string, string> = {
${entries}
};
`;
}

function emitForecast(counties) {
  const m = data.meta;
  const s = data.statewide;
  const t = data.turnout;

  const rows = counties
    .map(
      (c) => `  {
    fips: "${c.fips}",
    name: ${JSON.stringify(c.name)},
    region: ${JSON.stringify(c.region)},
    projectedTurnout: ${c.projectedTurnout},
    shareOfElectorate: ${c.shareOfElectorate},
    donalds: ${c.donalds},
    fishback: ${c.fishback},
    collins: ${c.collins},
    renner: ${c.renner},
    other: ${c.other},
    margin: ${c.margin},
    leader: "${c.leader}",
    runnerUp: "${c.runnerUp}",
    ci90: [${c.ci90[0]}, ${c.ci90[1]}],
    tooCloseToCall: ${c.tooCloseToCall},
    donaldsVotes: ${c.donaldsVotes},
    fishbackVotes: ${c.fishbackVotes},
    collinsVotes: ${c.collinsVotes},
    rennerVotes: ${c.rennerVotes},
    otherVotes: ${c.otherVotes},
    interviews: ${c.interviews},
  },`
    )
    .join("\n");

  const regions = [...new Set(counties.map((c) => c.region))];

  return `/**
 * TPSI — Florida Republican Gubernatorial Primary
 * County-level baseline projection · Election August 18, 2026
 *
 * GENERATED by scripts/gen_fl_forecast.mjs from app/floridaprimary/flData.json.
 * DO NOT EDIT BY HAND — regenerate from the model pipeline.
 *
 * READ BEFORE USING COUNTY SHARES
 * The county layer is a *decomposition* of the statewide model, not 67
 * independent estimates: county shares are the statewide numbers reweighted by
 * each county's demographic composition, so summing the counties returns the
 * statewide topline exactly and adds no information to it. Statewide
 * probabilities must come from STATEWIDE_FORECAST, never from aggregating
 * county intervals — county errors share one dominant statewide swing term,
 * so adding their variances in quadrature understates the real spread by
 * roughly an order of magnitude.
 *
 * The county estimates carry almost no local sample: ${m.n} interviews spread
 * across 67 counties, a median of 3 per county and ${counties.filter((c) => c.interviews <= 1).length} counties at one or
 * fewer. They are also over-smoothed — demographic post-stratification cannot
 * reproduce home-county effects, media markets or ballot-order effects, so
 * between-county dispersion here is narrower than a real primary would show.
 * ${counties.filter((c) => c.tooCloseToCall).length} of 67 counties have a 90% margin interval that crosses zero.
 *
 * \`projectedTurnout\` is the load-bearing field and is materially more reliable
 * than any share: it derives from R registration and historical primary
 * turnout, not from the survey. It is what lets the board estimate how much
 * vote is outstanding and where.
 */

export type CandidateKey = "donalds" | "fishback" | "collins" | "renner" | "other";

/** Ballot-order-independent display order: model rank at the time of build. */
export const CANDIDATE_ORDER: CandidateKey[] = ["donalds", "fishback", "collins", "renner"];

export const CANDIDATE_NAMES: Record<CandidateKey, string> = {
  donalds: "Byron Donalds",
  fishback: "James Fishback",
  collins: "Jay Collins",
  renner: "Paul Renner",
  other: "Other candidates",
};

export const CANDIDATE_LAST: Record<CandidateKey, string> = {
  donalds: "Donalds",
  fishback: "Fishback",
  collins: "Collins",
  renner: "Renner",
  other: "Other",
};

/** Substring that identifies each candidate in the CivicAPI feed. */
export const CANDIDATE_MATCH: Record<Exclude<CandidateKey, "other">, string> = {
  donalds: "donalds",
  fishback: "fishback",
  collins: "collins",
  renner: "renner",
};

export type Region =
${regions.map((r) => `  | ${JSON.stringify(r)}`).join("\n")};

export interface CountyForecast {
  /** 5-digit state+county FIPS code */
  fips: string;
  name: string;
  region: Region;
  /** Modelled Republican primary ballots cast */
  projectedTurnout: number;
  /** Percent of the projected statewide electorate */
  shareOfElectorate: number;
  /** Vote shares, percent of all ballots cast in county */
  donalds: number;
  fishback: number;
  collins: number;
  renner: number;
  other: number;
  /** donalds − fishback, percentage points */
  margin: number;
  leader: CandidateKey;
  runnerUp: CandidateKey;
  /** 90% interval on \`margin\` */
  ci90: [number, number];
  /** True when ci90 straddles zero — do not report a county winner */
  tooCloseToCall: boolean;
  donaldsVotes: number;
  fishbackVotes: number;
  collinsVotes: number;
  rennerVotes: number;
  otherVotes: number;
  /** Completed interviews falling in this county. Frequently 0 or 1. */
  interviews: number;
}

export interface StatewideForecast {
  projectedTurnout: number;
  donalds: number;
  fishback: number;
  collins: number;
  renner: number;
  other: number;
  /** donalds − fishback, percentage points */
  margin: number;
  donaldsVotes: number;
  fishbackVotes: number;
  collinsVotes: number;
  rennerVotes: number;
  otherVotes: number;
  /** Simulated probability each candidate finishes first */
  winProbability: Record<Exclude<CandidateKey, "other">, number>;
  medianMargin: number;
  /** 90% interval on the simulated margin */
  margin90: [number, number];
  /** SD of the simulated Donalds−Fishback margin, percentage points */
  marginSd: number;
}

export interface TurnoutModel {
  registeredRepublicans: number;
  /** Ballots already banked by mail and early vote at model build */
  bankedBallots: number;
  projected: number;
  pctOfRegistered: number;
}

export interface ForecastMeta {
  model: string;
  electionDate: string;
  fieldDates: string;
  interviewsReported: number;
  marginOfError: number;
  countiesTooCloseToCall: number;
  raceRule: string;
}

export const FORECAST_META: ForecastMeta = {
  model: "TPSI Florida county baseline · demographic post-stratification",
  electionDate: "2026-08-18",
  fieldDates: ${JSON.stringify(m.field)},
  interviewsReported: ${m.n},
  marginOfError: ${m.moe},
  countiesTooCloseToCall: ${counties.filter((c) => c.tooCloseToCall).length},
  raceRule: "Plurality — no runoff",
};

export const TURNOUT_MODEL: TurnoutModel = {
  registeredRepublicans: ${t.reg_r},
  bankedBallots: ${m.banked},
  projected: ${s.total},
  pctOfRegistered: ${t.nom_pct},
};

export const STATEWIDE_FORECAST: StatewideForecast = {
  projectedTurnout: ${s.total},
  donalds: ${s.p.Donalds},
  fishback: ${s.p.Fishback},
  collins: ${s.p.Collins},
  renner: ${s.p.Renner},
  other: ${s.p.Other},
  margin: ${round(s.p.Donalds - s.p.Fishback, 2)},
  donaldsVotes: ${s.v.Donalds},
  fishbackVotes: ${s.v.Fishback},
  collinsVotes: ${s.v.Collins},
  rennerVotes: ${s.v.Renner},
  otherVotes: ${s.v.Other},
  winProbability: {
    donalds: ${m.win},
    fishback: ${m.win_fb},
    collins: ${m.win_col},
    renner: ${round(Math.max(0, 100 - m.win - m.win_fb - m.win_col), 2)},
  },
  medianMargin: ${m.median_margin},
  margin90: [${m.pct.p5}, ${m.pct.p95}],
  marginSd: ${m.total_sd},
};

/** All 67 counties, ordered by projected turnout descending. */
export const COUNTY_FORECASTS: CountyForecast[] = [
${rows}
];
`;
}

const fips = await fipsByName();
const counties = build(fips);

// Sanity gates — a silent mismatch here would ship a wrong board.
const missingFips = counties.filter((c) => !c.fips);
if (missingFips.length) throw new Error(`no FIPS for: ${missingFips.map((c) => c.name).join(", ")}`);
if (counties.length !== 67) throw new Error(`expected 67 counties, got ${counties.length}`);

const turnoutSum = counties.reduce((s, c) => s + c.projectedTurnout, 0);
if (Math.abs(turnoutSum - data.statewide.total) > 100) {
  throw new Error(`turnout sum ${turnoutSum} != statewide ${data.statewide.total}`);
}

fs.writeFileSync(path.join(OUT_DIR, "flCountyGeo.ts"), emitGeo());
fs.writeFileSync(path.join(OUT_DIR, "flCountyForecast.ts"), emitForecast(counties));

console.log(
  `wrote flCountyGeo.ts (67 paths) and flCountyForecast.ts\n` +
    `  turnout sum ${turnoutSum.toLocaleString()}\n` +
    `  too close to call ${counties.filter((c) => c.tooCloseToCall).length}/67\n` +
    `  counties with <=1 interview ${counties.filter((c) => c.interviews <= 1).length}`
);
