/**
 * Extracts South Carolina county geometry from the Census cb_500k SVG into a
 * TypeScript module, so the board renders it with no fetch and no XML parsing.
 *
 *   node scripts/gen_sc_geo.mjs
 *
 * The source <g> carries transform="translate(5,5)"; that is preserved in the
 * component rather than baked into the path data, so a re-run of this script
 * against a fresh download produces identical output.
 */

import { readFileSync, writeFileSync } from "node:fs";

const SRC = "changeorders/South_Carolina_county_map,_cb_500k.svg";
const OUT = "app/results/_data/scCountyGeo.ts";

const svg = readFileSync(SRC, "utf8");

const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
if (!viewBox) throw new Error("no viewBox on the source SVG");

const translate = svg.match(/<g[^>]*transform="translate\(([-\d.]+),\s*([-\d.]+)\)"/);
const [, tx = "0", ty = "0"] = translate ?? [];

const paths = {};
const re = /<path\s+d="([^"]+)"\s+id="([^"]+)"/g;
let m;
while ((m = re.exec(svg))) {
  const key = m[2].trim().toUpperCase();
  if (paths[key]) throw new Error(`duplicate county id in source SVG: ${key}`);
  // Collapse whitespace; the source pretty-prints the coordinate lists.
  paths[key] = m[1].replace(/\s+/g, " ").trim();
}

const count = Object.keys(paths).length;
if (count !== 46) throw new Error(`expected 46 South Carolina counties, extracted ${count}`);

const body = Object.entries(paths)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([k, d]) => `  ${JSON.stringify(k)}: ${JSON.stringify(d)},`)
  .join("\n");

writeFileSync(
  OUT,
  `// GENERATED by scripts/gen_sc_geo.mjs from ${SRC}. Do not edit by hand.
// Census cartographic boundary file, 1:500k. Keys are uppercase county names,
// matching the normalisation applied to CivicAPI region_results.

export const SC_VIEWBOX = ${JSON.stringify(viewBox)};

/** The source SVG nests its counties inside this offset. */
export const SC_TRANSLATE = ${JSON.stringify(`translate(${tx},${ty})`)};

export const SC_COUNTY_PATHS: Record<string, string> = {
${body}
};
`,
  "utf8",
);

console.log(`counties:  ${count}`);
console.log(`viewBox:   ${viewBox}`);
console.log(`transform: translate(${tx},${ty})`);
console.log(`wrote:     ${OUT}`);
