#!/usr/bin/env node
/**
 * Extracts the Oklahoma runoff forecast out of the scenario-engine HTML into
 * two TypeScript modules the results board can import.
 *
 * Source: changeorders/TPSI_OK_Runoff_County_Forecast_Map_FINAL2.html
 * Run:    node scripts/gen_ok_forecast.mjs
 *
 * The HTML is the model's own output, so it is the authority. Anything derived
 * here is arithmetic on its numbers, never a new estimate.
 */

import { readFileSync, writeFileSync } from "node:fs";

const SRC = "changeorders/TPSI_OK_Runoff_County_Forecast_Map_FINAL2.html";
const html = readFileSync(SRC, "utf8");

/** Pulls `const NAME={...}` by walking braces, so nested objects survive. */
function extractObject(source, marker) {
  const start = source.indexOf(marker);
  if (start < 0) throw new Error(`missing ${marker}`);
  let i = source.indexOf("{", start);
  let depth = 0;
  let inStr = false;
  let esc = false;
  for (let j = i; j < source.length; j++) {
    const ch = source[j];
    if (inStr) {
      if (esc) esc = false;
      else if (ch === "\\") esc = true;
      else if (ch === '"') inStr = false;
      continue;
    }
    if (ch === '"') inStr = true;
    else if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) return JSON.parse(source.slice(i, j + 1));
    }
  }
  throw new Error(`unterminated ${marker}`);
}

const D = extractObject(html, "const D=");
const viewBox = (html.match(/viewBox="([^"]+)"/) || [])[1];
if (!viewBox) throw new Error("missing viewBox");

const { meta, statewide, counties, geo } = D;
const names = Object.keys(statewide.p); // ["Drummond","Mazzei"]
if (names.length !== 2) throw new Error(`expected a two-way runoff, got ${names.length}`);
const [A, B] = names;
const keyOf = (n) => n.toLowerCase();

const countyList = Object.entries(counties).map(([key, c]) => ({
  key,
  name: c.name,
  region: c.region,
  projectedTurnout: c.votes,
  shares: { [keyOf(A)]: c.p[A], [keyOf(B)]: c.p[B] },
  votes: { [keyOf(A)]: c.v[A], [keyOf(B)]: c.v[B] },
  leader: keyOf(c.ld),
  runnerUp: keyOf(c.sd),
  margin: c.mg,
  ci90: [c.lo, c.hi],
  tooCloseToCall: c.lo < 0 && c.hi > 0,
  rating: c.rating,
  interviews: c.nobs,
  effectiveVoters: c.eff,
  turnoutIndex: c.tex,
}));

countyList.sort((a, b) => b.projectedTurnout - a.projectedTurnout);

const regions = [...new Set(countyList.map((c) => c.region))].sort();

// Reconciliation check: the county layer is a decomposition of the statewide
// model, so it must sum back to it. A drift here means the export is stale.
const sum = countyList.reduce(
  (acc, c) => ({
    a: acc.a + c.votes[keyOf(A)],
    b: acc.b + c.votes[keyOf(B)],
    t: acc.t + c.projectedTurnout,
  }),
  { a: 0, b: 0, t: 0 },
);
const drift = Math.abs(sum.t - statewide.total) / statewide.total;
if (drift > 0.02) throw new Error(`county turnout sums to ${sum.t}, statewide says ${statewide.total}`);

const ts = (v) => JSON.stringify(v);

const forecast = `/**
 * TPSI — Oklahoma Republican Gubernatorial Runoff
 * County-level baseline projection · Election August 25, 2026
 *
 * GENERATED by scripts/gen_ok_forecast.mjs from
 * ${SRC}
 * DO NOT EDIT BY HAND — regenerate from the model pipeline.
 *
 * READ BEFORE USING COUNTY SHARES
 * The county layer is a decomposition of the statewide model, not 77
 * independent estimates. County shares are the statewide numbers reweighted by
 * each county's composition, so they sum back to the statewide topline exactly
 * and add no information to it. Statewide probabilities must come from
 * STATEWIDE_FORECAST, never from aggregating county intervals — county errors
 * share one dominant statewide swing term, so adding their variances in
 * quadrature understates the real spread badly.
 *
 * ${meta.too_close} of ${countyList.length} counties have a 90% margin interval that crosses zero.
 * The poll behind this is n=${meta.n}, ±${meta.moe}, fielded ${meta.field} — a statewide
 * sample, not 77 county samples.
 *
 * \`projectedTurnout\` is the load-bearing field and is far more reliable than
 * any county share: it comes from registration and past runoff turnout, not
 * from the survey. It is what lets the board estimate how much vote is still
 * outstanding and where.
 */

export type CandidateKey = ${names.map((n) => `"${keyOf(n)}"`).join(" | ")};

export const CANDIDATE_ORDER: CandidateKey[] = [${names.map((n) => `"${keyOf(n)}"`).join(", ")}];

export const CANDIDATE_NAMES: Record<CandidateKey, string> = {
  ${keyOf(A)}: "Gentner Drummond",
  ${keyOf(B)}: "Mike Mazzei",
};

export const CANDIDATE_LAST: Record<CandidateKey, string> = {
  ${keyOf(A)}: ${ts(A)},
  ${keyOf(B)}: ${ts(B)},
};

/** Substring that identifies each candidate in the CivicAPI feed. */
export const CANDIDATE_MATCH: Record<CandidateKey, string> = {
  ${keyOf(A)}: ${ts(keyOf(A))},
  ${keyOf(B)}: ${ts(keyOf(B))},
};

export type Region = ${regions.map(ts).join(" | ")};

export interface CountyForecast {
  key: string;
  name: string;
  region: Region;
  projectedTurnout: number;
  shares: Record<CandidateKey, number>;
  votes: Record<CandidateKey, number>;
  leader: CandidateKey;
  runnerUp: CandidateKey;
  /** leader − runnerUp, percentage points. Always >= 0. */
  margin: number;
  /** 90% interval on ${A}'s margin. Negative means ${B} ahead. */
  ci90: [number, number];
  tooCloseToCall: boolean;
  rating: string;
  interviews: number;
  effectiveVoters: number;
  turnoutIndex: number;
}

export const COUNTY_FORECASTS: CountyForecast[] = ${JSON.stringify(countyList, null, 2)};

export const STATEWIDE_FORECAST = {
  ${keyOf(A)}: ${statewide.p[A]},
  ${keyOf(B)}: ${statewide.p[B]},
  votes: { ${keyOf(A)}: ${statewide.v[A]}, ${keyOf(B)}: ${statewide.v[B]} },
  leader: ${ts(keyOf(statewide.lead))} as CandidateKey,
  runnerUp: ${ts(keyOf(statewide.runner))} as CandidateKey,
  /** ${A} − ${B}, percentage points. */
  margin: ${meta.median_margin},
  /** Standard deviation of that margin. This is the number that governs calls. */
  marginSd: ${meta.total_sd},
  /** 90% interval on the margin. */
  ci90: [${meta.pct.p5}, ${meta.pct.p95}] as [number, number],
  winProbability: { ${keyOf(A)}: ${meta.win}, ${keyOf(B)}: ${meta.win_m} },
};

export const TURNOUT_MODEL = {
  /** Registered Republicans. */
  registered: ${meta.reg_r},
  /** Ballots cast in the June first round. */
  firstRound: ${meta.june},
  /** Median projected runoff turnout. */
  projected: ${meta.turnout.median},
  /** Projected turnout as a share of registered Republicans. */
  pctOfRegistered: ${meta.turnout.pct_rv},
};

export const FORECAST_META = {
  interviewsReported: ${meta.n},
  marginOfError: ${meta.moe},
  fieldDates: ${ts(meta.field)},
  countiesTooCloseToCall: ${meta.too_close},
  countyCount: ${countyList.length},
  /** Between-county residual SD, points. */
  tau: ${meta.tau},
  raceRule: "PLURALITY" as const,
};
`;

const geoEntries = Object.entries(geo).map(([k, d]) => `  ${ts(k)}: ${ts(d)},`);
const geoTs = `/**
 * Oklahoma county outlines, baked from
 * ${SRC}
 * GENERATED by scripts/gen_ok_forecast.mjs — do not edit by hand.
 *
 * Pre-projected SVG path data keyed by uppercase county name, so the board
 * needs no projection maths at runtime.
 */

export const OK_VIEWBOX = ${ts(viewBox)};

export const OK_COUNTY_PATHS: Record<string, string> = {
${geoEntries.join("\n")}
};
`;

writeFileSync("app/results/_data/okCountyForecast.ts", forecast);
writeFileSync("app/results/_data/okCountyGeo.ts", geoTs);

console.log(`counties:      ${countyList.length}`);
console.log(`regions:       ${regions.length}`);
console.log(`geo paths:     ${Object.keys(geo).length}`);
console.log(`statewide:     ${A} ${statewide.p[A]} / ${B} ${statewide.p[B]}`);
console.log(`turnout:       ${statewide.total} (sum ${sum.t}, drift ${(drift * 100).toFixed(2)}%)`);
console.log(`win prob:      ${A} ${meta.win}% / ${B} ${meta.win_m}%`);
console.log(`too close:     ${meta.too_close}/${countyList.length}`);
