#!/usr/bin/env python3
"""Port the Florida scenario-engine prototype into app/floridaprimary/.

The prototype in changeorders/ is a single self-contained HTML file. The site
serves the same engine as a React-mounted module, so this script performs the
three mechanical edits that separate the two — extract the data blob, prefix the
container ids, and swap the fixed palette for theme-aware swatches — instead of
those edits being redone by hand every time the prototype is revised.

  python3 scripts/port_fl_engine.py changeorders/TPSI_FL_Scenario_Engine_v3.html
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "app" / "floridaprimary"

# Ids that live in FloridaPrimary.tsx and so must not collide with global site
# ids. Ids minted inside innerHTML strings stay unprefixed.
CONTAINER_IDS = [
    "presets", "left", "right", "tabs", "map", "tip",
    "ctnote", "ctwrap", "ctbl", "expandAll",
]


def brace_match(s: str, start: int) -> int:
    """Index just past the object literal opening at s[start]."""
    depth, in_str, esc = 0, None, False
    for i in range(start, len(s)):
        ch = s[i]
        if in_str:
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == in_str:
                in_str = None
            continue
        if ch in "\"'":
            in_str = ch
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return i + 1
    raise ValueError("unbalanced braces")


def main() -> int:
    src = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else ROOT / "changeorders/TPSI_FL_Scenario_Engine_v3.html"
    html = src.read_text(encoding="utf-8")

    body = html[html.index("<script>") + len("<script>"):]
    body = body[:body.index("</script>")]

    # 1. Data blob -> flData.json
    b_start = body.index("const B=") + len("const B=")
    b_end = brace_match(body, b_start)
    data = json.loads(body[b_start:b_end])
    (OUT_DIR / "flData.json").write_text(
        json.dumps(data, separators=(",", ":")), encoding="utf-8")

    # Drop the blob and any trailing semicolon from the script we keep.
    script = (body[:body.index("const B=")] + body[b_end:]).lstrip(";\n ")

    # 2. Fixed palette -> theme-aware swatches.
    co = re.search(r"const CO=\{[^}]*\};?", script)
    if not co:
        raise SystemExit("could not find the CO palette in the prototype")
    script = script.replace(co.group(0), "let CO=isDarkTheme()?CO_DARK:CO_LIGHT;")

    # render() is the single entry point for every repaint, so re-reading the
    # palette there is what makes a live theme toggle recolour the board.
    if "function render(){" not in script:
        raise SystemExit("could not find render() to hook the palette refresh into")
    script = script.replace("function render(){",
                            "function render(){\nCO=isDarkTheme()?CO_DARK:CO_LIGHT;", 1)

    # 3. Container ids.
    for cid in CONTAINER_IDS:
        script = script.replace(f"getElementById('{cid}')", f"getElementById('fl-{cid}')")
        script = re.sub(rf"""id=(\\?)(["']){cid}\2""", rf"""id=\1\2fl-{cid}\2""", script)

    script = "\n".join("  " + ln if ln.strip() else ln for ln in script.split("\n"))

    header = f'''// GENERATED by scripts/port_fl_engine.py from {src.relative_to(ROOT)} — do not hand-edit.
// Re-run the script after revising the prototype. Imperative DOM code is kept
// as-is so the math stays byte-for-byte with the reference build.
import B from "./flData.json";

// The prototype ships one fixed light palette. These are its exact hues, plus a
// lifted set for dark mode where the originals fall below usable contrast.
const CO_LIGHT = {{ Donalds: "#B23A2E", Fishback: "#1E6E86", Collins: "#6D4B96", Renner: "#A87516", Other: "#8A929C" }};
const CO_DARK = {{ Donalds: "#E06A5B", Fishback: "#4FA8C4", Collins: "#A98BD6", Renner: "#D9A83F", Other: "#9AA0AC" }};
function isDarkTheme() {{
  return typeof document !== "undefined" && document.documentElement.getAttribute("data-theme") === "dark";
}}

export function initFloridaEngine() {{
'''
    footer = '''
  // Re-render on theme toggle so the map, legend and table recolour live.
  const themeObserver = new MutationObserver(() => render());
  themeObserver.observe(document.documentElement, { attributes: true, attributeFilter: ["data-theme"] });

  return () => themeObserver.disconnect();
}
'''
    (OUT_DIR / "flEngine.js").write_text(header + script + footer, encoding="utf-8")

    print(f"flData.json  {len(json.dumps(data, separators=(',', ':'))):>8,} bytes  {len(data)} keys")
    print(f"flEngine.js  {len(header + script + footer):>8,} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
